language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  # -coverage run -m --source app, instance nosetest
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls