language: python

python:
  - "3.6"

  cache: pip

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

addons: 
  postgresql: "10.5"

before_script:
  - psql -c 'CREATE DATABASE fastfoodtest_db' -U postgres
  - psql -c "GRANT ALL PRIVILEDGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  # -coverage run -m --source app, instance nosetest
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls